CREATE TABLE "TEST"."BUSINESS_STATISTICS"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"REGION_NAME" VARCHAR(10),
"STATISTICS_DATE" TIMESTAMP(0),
"BOOK_NUM" INT,
"CANCEL_NUM" INT,
"CANCEL_AMOUNT" FLOAT,
"REVOKE_NUM" INT,
"SUCCESS_AMOUNT" FLOAT,
"TYPE" CHAR(2),
UNIQUE("ID"),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST"."BUSINESS_STATISTICS" IS '业务统计';
COMMENT ON COLUMN "TEST"."BUSINESS_STATISTICS"."BOOK_NUM" IS '订坐数';
COMMENT ON COLUMN "TEST"."BUSINESS_STATISTICS"."CANCEL_AMOUNT" IS '退订金额(单位/元)';
COMMENT ON COLUMN "TEST"."BUSINESS_STATISTICS"."CANCEL_NUM" IS '退订数';
COMMENT ON COLUMN "TEST"."BUSINESS_STATISTICS"."STATISTICS_DATE" IS '日期';
COMMENT ON COLUMN "TEST"."BUSINESS_STATISTICS"."REGION_NAME" IS '所属地区';
COMMENT ON COLUMN "TEST"."BUSINESS_STATISTICS"."REVOKE_NUM" IS '撤销数';
COMMENT ON COLUMN "TEST"."BUSINESS_STATISTICS"."SUCCESS_AMOUNT" IS '成交金额(单位/元)';
COMMENT ON COLUMN "TEST"."BUSINESS_STATISTICS"."TYPE" IS '系统类型';


CREATE TABLE "TEST"."BUY_EARLY_STATISTICS"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"REGION_NAME" VARCHAR(10),
"EARLY_ONE_HOUR" INT,
"EARLY_EIGHT" INT,
"EARLY_SIXTEEN" INT,
"EARLY_ONE_DAY" INT,
"EARLY_TWO_DAY" INT,
"EARLY_TWO_DAY_OVER" INT,
"STATISTICS_DATE" TIMESTAMP(0),
"TYPE" CHAR(2),
UNIQUE("ID"),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST"."BUY_EARLY_STATISTICS" IS '提前购票统计';
COMMENT ON COLUMN "TEST"."BUY_EARLY_STATISTICS"."STATISTICS_DATE" IS '日期';
COMMENT ON COLUMN "TEST"."BUY_EARLY_STATISTICS"."EARLY_EIGHT" IS '提前8小时人数';
COMMENT ON COLUMN "TEST"."BUY_EARLY_STATISTICS"."EARLY_ONE_DAY" IS '提前1天';
COMMENT ON COLUMN "TEST"."BUY_EARLY_STATISTICS"."EARLY_ONE_HOUR" IS '提前1小时人数';
COMMENT ON COLUMN "TEST"."BUY_EARLY_STATISTICS"."EARLY_SIXTEEN" IS '提前16小时人数';
COMMENT ON COLUMN "TEST"."BUY_EARLY_STATISTICS"."EARLY_TWO_DAY" IS '提前2天';
COMMENT ON COLUMN "TEST"."BUY_EARLY_STATISTICS"."EARLY_TWO_DAY_OVER" IS '提前2天以上';
COMMENT ON COLUMN "TEST"."BUY_EARLY_STATISTICS"."REGION_NAME" IS '所属地区';
COMMENT ON COLUMN "TEST"."BUY_EARLY_STATISTICS"."TYPE" IS '系统类型';


CREATE TABLE "TEST"."END_SEARCH_RATE_STATISTICS"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"REGION_NAME" VARCHAR(10),
"STATISTICS_DATE" TIMESTAMP(0),
"END_NAME" VARCHAR(20),
"SEARCH_COUNT" INT,
"TYPE" CHAR(2),
UNIQUE("ID"),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST"."END_SEARCH_RATE_STATISTICS" IS '终点站搜索频率统计';
COMMENT ON COLUMN "TEST"."END_SEARCH_RATE_STATISTICS"."STATISTICS_DATE" IS '日期';
COMMENT ON COLUMN "TEST"."END_SEARCH_RATE_STATISTICS"."END_NAME" IS '终点站名';
COMMENT ON COLUMN "TEST"."END_SEARCH_RATE_STATISTICS"."REGION_NAME" IS '所属地区';
COMMENT ON COLUMN "TEST"."END_SEARCH_RATE_STATISTICS"."SEARCH_COUNT" IS '搜索次数';
COMMENT ON COLUMN "TEST"."END_SEARCH_RATE_STATISTICS"."TYPE" IS '系统类型';


CREATE TABLE "TEST"."LINE_SEARCH_RATE_STATISTICS"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"STATISTICS_DATE" TIMESTAMP(0),
"REGION_NAME" VARCHAR(10),
"START_NAME" VARCHAR(20),
"END_NAME" VARCHAR(20),
"SEARCH_COUNT" INT,
"ENABLE_SALE_TOTAL" INT,
"ENABLE_SALE_AVG" VARCHAR(20),
"TYPE" CHAR(2),
UNIQUE("ID"),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST"."LINE_SEARCH_RATE_STATISTICS" IS '线路搜索频率统计';
COMMENT ON COLUMN "TEST"."LINE_SEARCH_RATE_STATISTICS"."STATISTICS_DATE" IS '日期';
COMMENT ON COLUMN "TEST"."LINE_SEARCH_RATE_STATISTICS"."ENABLE_SALE_AVG" IS '平均可售班次数';
COMMENT ON COLUMN "TEST"."LINE_SEARCH_RATE_STATISTICS"."ENABLE_SALE_TOTAL" IS '合计可售班次数';
COMMENT ON COLUMN "TEST"."LINE_SEARCH_RATE_STATISTICS"."END_NAME" IS '终点站名';
COMMENT ON COLUMN "TEST"."LINE_SEARCH_RATE_STATISTICS"."REGION_NAME" IS '所属地区';
COMMENT ON COLUMN "TEST"."LINE_SEARCH_RATE_STATISTICS"."SEARCH_COUNT" IS '搜索次数';
COMMENT ON COLUMN "TEST"."LINE_SEARCH_RATE_STATISTICS"."START_NAME" IS '起始站名';
COMMENT ON COLUMN "TEST"."LINE_SEARCH_RATE_STATISTICS"."TYPE" IS '系统类型';


CREATE TABLE "TEST"."MODEL_CLICK_STATISTICS"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"MODEL_NAME" VARCHAR(50),
"CLICK_COUNT" INT,
"STATISTICS_DATE" TIMESTAMP(0),
"TYPE" CHAR(2),
UNIQUE("ID"),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST"."MODEL_CLICK_STATISTICS" IS '模块点击统计';
COMMENT ON COLUMN "TEST"."MODEL_CLICK_STATISTICS"."CLICK_COUNT" IS '点击数';
COMMENT ON COLUMN "TEST"."MODEL_CLICK_STATISTICS"."STATISTICS_DATE" IS '日期';
COMMENT ON COLUMN "TEST"."MODEL_CLICK_STATISTICS"."MODEL_NAME" IS '模块名';
COMMENT ON COLUMN "TEST"."MODEL_CLICK_STATISTICS"."TYPE" IS '系统类型';


CREATE TABLE "TEST"."REAL_LOAD_STATISTICS"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"REGION_NAME" VARCHAR(10),
"REAL_LOAD_RATE" VARCHAR(10),
"STATISTICS_DATE" TIMESTAMP(0),
"TYPE" CHAR(2),
UNIQUE("ID"),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST"."REAL_LOAD_STATISTICS" IS '实载率统计';
COMMENT ON COLUMN "TEST"."REAL_LOAD_STATISTICS"."STATISTICS_DATE" IS '日期';
COMMENT ON COLUMN "TEST"."REAL_LOAD_STATISTICS"."REAL_LOAD_RATE" IS '实载率(单位%)';
COMMENT ON COLUMN "TEST"."REAL_LOAD_STATISTICS"."REGION_NAME" IS '所属地区';
COMMENT ON COLUMN "TEST"."REAL_LOAD_STATISTICS"."TYPE" IS '系统类型';


CREATE TABLE "TEST"."START_SEARCH_RATE_STATISTICS"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"STATISTICS_DATE" TIMESTAMP(0),
"REGION_NAME" VARCHAR(10),
"START_NAME" VARCHAR(20),
"SEARCH_COUNT" INT,
"TYPE" CHAR(2),
UNIQUE("ID"),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST"."START_SEARCH_RATE_STATISTICS" IS '起始站搜索频率统计';
COMMENT ON COLUMN "TEST"."START_SEARCH_RATE_STATISTICS"."STATISTICS_DATE" IS '日期';
COMMENT ON COLUMN "TEST"."START_SEARCH_RATE_STATISTICS"."REGION_NAME" IS '所属地区';
COMMENT ON COLUMN "TEST"."START_SEARCH_RATE_STATISTICS"."SEARCH_COUNT" IS '搜索次数';
COMMENT ON COLUMN "TEST"."START_SEARCH_RATE_STATISTICS"."START_NAME" IS '起始站名';
COMMENT ON COLUMN "TEST"."START_SEARCH_RATE_STATISTICS"."TYPE" IS '系统类型';


CREATE TABLE "TEST"."USER_AGE_SPREAD_STATISTICS"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"STATISTICS_DATE" TIMESTAMP(0),
"AGE_RANGE_ONE" INT,
"AGE_RANGE_TWO" INT,
"AGE_RANGE_THIRD" INT,
"AGE_RANGE_FOUR" INT,
"AGE_RANGE_FIVE" INT,
"AGE_RANGE_SIX" INT,
"TYPE" CHAR(2),
UNIQUE("ID"),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST"."USER_AGE_SPREAD_STATISTICS" IS '用户年龄分布统计';
COMMENT ON COLUMN "TEST"."USER_AGE_SPREAD_STATISTICS"."AGE_RANGE_FIVE" IS '40~49岁人数';
COMMENT ON COLUMN "TEST"."USER_AGE_SPREAD_STATISTICS"."AGE_RANGE_FOUR" IS '30~39岁人数';
COMMENT ON COLUMN "TEST"."USER_AGE_SPREAD_STATISTICS"."AGE_RANGE_ONE" IS '17岁以下人数';
COMMENT ON COLUMN "TEST"."USER_AGE_SPREAD_STATISTICS"."AGE_RANGE_SIX" IS '50岁以上人数';
COMMENT ON COLUMN "TEST"."USER_AGE_SPREAD_STATISTICS"."AGE_RANGE_THIRD" IS '25~29岁人数';
COMMENT ON COLUMN "TEST"."USER_AGE_SPREAD_STATISTICS"."AGE_RANGE_TWO" IS '18~24岁人数';
COMMENT ON COLUMN "TEST"."USER_AGE_SPREAD_STATISTICS"."STATISTICS_DATE" IS '日期';
COMMENT ON COLUMN "TEST"."USER_AGE_SPREAD_STATISTICS"."TYPE" IS '系统类型';


CREATE TABLE "TEST"."USER_SEX_SPREAD_STATISTICS"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"TYPE" CHAR(2),
"STATISTICS_DATE" TIMESTAMP(0),
"WOMAN_NUM" INT,
"MAN_NUM" INT,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST"."USER_SEX_SPREAD_STATISTICS" IS '用户性别分布统计';
COMMENT ON COLUMN "TEST"."USER_SEX_SPREAD_STATISTICS"."STATISTICS_DATE" IS '日期';
COMMENT ON COLUMN "TEST"."USER_SEX_SPREAD_STATISTICS"."MAN_NUM" IS '男性数量';
COMMENT ON COLUMN "TEST"."USER_SEX_SPREAD_STATISTICS"."TYPE" IS '系统类型';
COMMENT ON COLUMN "TEST"."USER_SEX_SPREAD_STATISTICS"."WOMAN_NUM" IS '女性数量';

CREATE TABLE "TEST"."OPRATION_STATISTICS"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"TRADE_AMOUNT" VARCHAR(10),
"TRADE_COUNT" INT,
"TRADE_NUM" INT,
"TRADE_NUM_FIRST" INT,
"TRADE_DATE" TIMESTAMP(0),
"TYPE" CHAR(2),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "TEST", CLUSTERBTR) ;

COMMENT ON TABLE "TEST"."OPRATION_STATISTICS" IS '运营统计';
COMMENT ON COLUMN "TEST"."OPRATION_STATISTICS"."TRADE_AMOUNT" IS '交易金额(单位/万元)';
COMMENT ON COLUMN "TEST"."OPRATION_STATISTICS"."TRADE_COUNT" IS '交易笔数';
COMMENT ON COLUMN "TEST"."OPRATION_STATISTICS"."TRADE_DATE" IS '交易日期';
COMMENT ON COLUMN "TEST"."OPRATION_STATISTICS"."TRADE_NUM" IS '交易人数';
COMMENT ON COLUMN "TEST"."OPRATION_STATISTICS"."TRADE_NUM_FIRST" IS '首次交易人数';
COMMENT ON COLUMN "TEST"."OPRATION_STATISTICS"."TYPE" IS '系统类型';



